### ISSUE TITLE
16x Perf regression 2.4.0 -> 2.4.1

### ISSUE THREAD

**Issue by BrianMar** [microsoft/beachball#534] opened 2021-06-15 19:35 UTC
We recently updated from 1.51 to 2.5.1. In doing so, we've started seeing a huge increase in the time taken to run beachball. For example, running "sync" takes ~33 seconds when I use version 1.51. The same command with 2.5.1 takes over 8 minutes. Our version bumps under 2.5.1 are taking over 30 minutes on some boxes, compared to under a minute previously. I've tried 2.6.1, but that appears to have the same performance characteristics as 2.5.1.

This is a rush repo with ~70 projects in it.

**Comment by JasonGore** [comment] 2021-06-15 20:07
This seems to be a very recent regression introduced in 2.4.1. These are the times I'm seeing:

| beachball version | time |
|-------------------|-----|
| 2.4.0 | 20 s |
| 2.4.1 | 3+ minutes |
| 2.5.0 | 3+ minutes |

Anecdotally I'm seeing `git-remote-https` flashing in my Mac terminal and it's oscillating at a much slower rate than it does with 2.4.0 and earlier.

**Comment by JasonGore** [comment] 2021-06-15 20:16
These are the two commits introduced with v2.4.1:
* [Validate the dependentChangeType field](https://github.com/microsoft/beachball/commit/895323e59aa11cfebf2a6eee0edfaec18f932d51)
* [Change files](https://github.com/microsoft/beachball/commit/03d1849570e6db63d9a38b64113d0d7162d47344)

**Comment by JasonGore** [comment] 2021-06-15 20:20
@kenotron I suspect this might be the workspace-tools update since I'm not seeing what could have affected this with the "Change files" commit

**Comment by kenotron** [comment] 2021-06-22 16:03
getPackageInfos() got super slow because "getDefaultRemoteBranch" now has to do a `git remote show`. Will have a fix for this shortly

**Closed** 2021-06-22 20:42 UTC
