### ISSUE TITLE
Beachball tries to merge no changes

### ISSUE THREAD

**Issue by viditganpi** [microsoft/beachball#716] opened 2022-08-08 08:27 UTC
Currently beachball does not have a mechanism to exit early and not perform any bump or publish in case there are no change files for non private packages. This later causes the publish command to fail at merge step, as there is nothing to merge.
A check should be added before bump and publish to tackle this case.

**Comment by ecraig12345** [comment] 2022-08-08 23:08
Probably a duplicate of #597. Beachball already exits early if there are no change files at all.

**Comment by viditganpi** [comment] 2022-08-09 09:51
Yes, but it should also exit early in case there is change files only for private packages

**Comment by ecraig12345** [comment] 2022-08-09 18:16
Yes, that’s what the other issue is about. Until that’s fixed, you can delete the bad change files to avoid the problem. (I’ve usually only seen that happen around the time a package is initially changed from private to published.)

**Closed by ecraig12345** 2022-08-09 18:16 UTC
